### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by payoto** [parcoor/py-propagsim#1]
Hey @manuel-capel , 
Nice work so far! What license do you want to publish this under? MIT maybe?

**Comment by MikeHatchi** [comment]
Hello @payoto @mancap314 , je pencherais plus pour GNU GPLv3:
"The GNU GPLv3 also lets people do almost anything they want with your project, except distributing closed source versions. (Ansible, Bash, and GIMP use the GNU GPLv3.)"

Je trouve le "except distributing closed source versions" intéressant.

**Comment by manuel-capel** [comment]
La seule différence avec la licence GNU c'est, comme tu le précises, l'interdiction de distribuer une version qui contiendrait du code propriétaire ("closed source"). Pourquoi l'interdire? (Question ouverte)
Si quelqu'un veut distribuer une version de ce projet qui contiendrait une implémentation propriétaire en SAS, pour SAP ou que sais-je, pourquoi pas?
